postMerge :
  preRun: 
    command:
      - npm install
      - npm run build
      - node test/prepare-jest.js
      
  
  subModules:          #Not to be changed
      
        
      - name: frontend      
        path : "./"
        pattern: 
          - "./test/frontend.spec.js"
        
        framework : jest
        runPreRunEveryTime: true
        preRun:
          env:
            TEST_FRONTEND: 1
          command:
            - node test/prepare-jest.js
            
        
        configFile : "./config/jest-frontend.config.js"
        
      - name: backend      
        path : "./"
        pattern: 
          - "./test/backend.spec.js"
        
        framework : jest
        runPreRunEveryTime: true
        preRun:
          env:
            TEST_BACKEND: 1
          command:
            - node test/prepare-jest.js
            
        
        configFile : "./config/jest-backend.config.js"  
      
        
      
        
preMerge : 
  
  subModules:          #Not to be changed
  
     - name: frontend      
        path : "./"
        pattern: 
          - "./test/frontend.spec.js"
        
        framework : jest
        runPreRunEveryTime: true
        preRun:
          env:
            TEST_FRONTEND: 1
          command:
            - node test/prepare-jest.js
            
        
        configFile : "./config/jest-frontend.config.js"
        
      - name: backend      
        path : "./"
        pattern: 
          - "./test/backend.spec.js"
        
        framework : jest
        runPreRunEveryTime: true
        preRun:
          env:
            TEST_BACKEND: 1
          command:
            - node test/prepare-jest.js
            
        
        configFile : "./config/jest-backend.config.js"  
        
  
version : 2.0
nodeVersion : 17.3.1
